# Generated by Django 5.2.4 on 2025-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed', '0004_childvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='relationship',
            field=models.CharField(default='Mother', max_length=100),
            preserve_default=False,
        ),
    ]
