# Generated by Django 5.2.4 on 2025-07-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposed', '0005_child_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTSSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('test_type', models.CharField(choices=[('DBS', 'Dried Blood Spot'), ('Rapid', 'Rapid Test'), ('PCR', 'PCR Test'), ('Other', 'Other')], max_length=10)),
                ('sample_id', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Inconclusive', 'Inconclusive')], max_length=20)),
                ('date_received', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hts_samples', to='children.child')),
            ],
        ),
    ]
