# ...existing code...
INSTALLED_APPS = [
    # ...existing apps...
    # Remove or correct this line:
    # 'TingatheCardswidget_tweaks',
    # If you want to use widget_tweaks, use:
    # 'widget_tweaks',
    # ...existing apps...
]
# ...existing code...