# Generated by Django 5.2.4 on 2025-08-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pact', '0007_guardian_vl_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField()),
                ('hiv_status', models.CharField(choices=[('POSITIVE', 'HIV Positive'), ('NEGATIVE', 'HIV Negative'), ('UNKNOWN', 'Unknown'), ('EXPOSED', 'HIV Exposed')], default='UNKNOWN', max_length=8)),
                ('date_tested', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pact.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('HVL', 'HVL Client Card'), ('BACK', 'Back to Care Client Card'), ('NEW', 'New Initiation Client Card')], max_length=5)),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed Service'), ('DIED', 'Died'), ('TRANSFERRED', 'Transferred Out'), ('STOPPED', 'Treatment Stopped')], default='IN_PROGRESS', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pact.patient')),
            ],
        ),
    ]
