# Generated by Django 5.2.4 on 2025-08-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingathe_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='unique_id',
            field=models.CharField(default='hvl', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientcard',
            name='card_type',
            field=models.CharField(choices=[('hvl', 'HVL Client Card'), ('b2c', 'Back to Care Client Card'), ('new_initiation', 'New Initiation Client Card')], max_length=14),
        ),
        migrations.AlterField(
            model_name='clientcard',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('Complete', 'Alive'), ('DIED', 'Died'), ('TRANSFERRED', 'Transferred Out'), ('STOPPED', 'Treatment Stopped')], default='IN_PROGRESS', max_length=12),
        ),
    ]
