# Generated by Django 5.2.4 on 2025-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingathe_tools', '0002_clientcard_unique_id_alter_clientcard_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcard',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('Complete', 'Complete'), ('DIED', 'Died'), ('TRANSFERRED', 'Transferred Out'), ('STOPPED', 'Treatment Stopped')], default='IN_PROGRESS', max_length=12),
        ),
    ]
