# Generated by Django 5.2.4 on 2025-07-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pact', '0007_guardian_vl_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('teen_range', models.CharField(choices=[('10-19', '10-19')], max_length=5)),
                ('session_type', models.CharField(choices=[('Guardian', 'Guardian'), ('Teen Only', 'Teen Only')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_in_teen', models.BooleanField()),
                ('purpose', models.CharField(choices=[('Clinic', 'Clinic'), ('Support', 'Support')], max_length=7)),
                ('guardian_present', models.BooleanField()),
                ('school', models.CharField(choices=[('No', 'No'), ('Yes, Day', 'Yes, Day'), ('Yes, BRD', 'Yes, BRD')], max_length=8)),
                ('vl_drawn', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pact.patient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teen_club.session')),
            ],
        ),
    ]
