# Generated by Django 5.2.4 on 2025-07-30 21:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0007_guardian_vl_status'),
        ('teen_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-arrived_at']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_date']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='arrived_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='session',
            name='facilitator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'patient')},
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('session_date', 'teen_range'), name='unique_sessions'),
        ),
    ]
