# Generated by Django 5.2.4 on 2025-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teen_club', '0002_alter_attendance_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='village',
            field=models.CharField(default='Chapola', max_length=255),
            preserve_default=False,
        ),
    ]
