# Generated by Django 5.2.4 on 2025-10-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teen_club', '0003_attendance_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sign_updated',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tracing_updated',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
