# Generated by Django 5.2.4 on 2025-08-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pact', '0009_patient_notes_alter_patient_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_entered', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('with_phone', models.BooleanField(default=False)),
                ('home_traced', models.BooleanField(default=False)),
                ('tracing_outcome', models.BooleanField(default=False)),
                ('final_outcome', models.CharField(max_length=100)),
                ('chw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracings', to='pact.staff')),
            ],
        ),
    ]
