# Generated by Django 5.2.4 on 2025-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracing',
            name='art_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
