# Generated by Django 5.2.4 on 2025-09-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0002_tracing_art_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateTimeField()),
                ('person_met', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_tracings', to='tracing.tracing')),
            ],
            options={
                'db_table': 'hometracing',
            },
        ),
        migrations.CreateModel(
            name='PhoneTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_called', models.DateTimeField()),
                ('person_called', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_tracings', to='tracing.tracing')),
            ],
            options={
                'db_table': 'phonetracing',
            },
        ),
    ]
