# Generated by Django 5.2.4 on 2025-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0003_hometracing_phonetracing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometracing',
            name='person_met',
        ),
        migrations.RemoveField(
            model_name='phonetracing',
            name='person_called',
        ),
        migrations.AlterField(
            model_name='hometracing',
            name='outcome',
            field=models.CharField(choices=[('found_house_talked', 'Found House and Talked to Client'), ('found_house_not_home', 'Found House but Client Not Home'), ('house_not_found', 'House Not Found')], max_length=100),
        ),
        migrations.AlterField(
            model_name='phonetracing',
            name='outcome',
            field=models.CharField(choices=[('talked_to_client', 'Talked to Client'), ('wrong_number', "wrong Number/Didn't Know Client"), ('no_answer', 'No Answer'), ('out_of_network', 'Out of Network'), ('line_busy', 'Line Busy')], max_length=100),
        ),
    ]
