# Generated by Django 5.2.4 on 2025-09-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0004_remove_hometracing_person_met_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracing',
            name='by_motorbike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracing',
            name='outcome_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracing',
            name='tracing_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
