# Generated by Django 5.2.4 on 2025-09-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0005_tracing_by_motorbike_tracing_outcome_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracing',
            name='phone_called',
            field=models.BooleanField(default=False),
        ),
    ]
