# Generated by Django 5.2.4 on 2025-09-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0006_tracing_phone_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracing',
            name='final_outcome',
            field=models.CharField(blank=True, choices=[('came_back', 'Came Back'), ('attended_appointment', 'Attended Appointment'), ('transferred_out', 'Transferred Out'), ('moved', 'Moved'), ('refused', 'Declined/Refused'), ('died', 'Died'), ('not_found', 'Not Found'), ('out', 'Outside Tracing Area'), ('did_not_return', 'Did Not Return')], max_length=100, null=True),
        ),
    ]
