# Generated by Django 5.2.4 on 2025-09-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0007_alter_tracing_final_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracing',
            name='tracing_updated',
            field=models.BooleanField(default=False),
        ),
    ]
