# Generated by Django 5.2.4 on 2025-09-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0008_tracing_tracing_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracing',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tracing',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tracing',
            name='mother_art',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
