# Generated by Django 5.2.4 on 2025-09-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0009_tracing_age_tracing_gender_tracing_mother_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracing',
            name='mother_art',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
