# Generated by Django 5.2.4 on 2025-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0010_alter_tracing_mother_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracing',
            name='mother_art',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
