# Generated by Django 5.2.4 on 2025-09-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0012_alter_tracing_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracing',
            name='date_entered',
            field=models.DateTimeField(),
        ),
    ]
