# Generated by Django 5.2.4 on 2025-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0013_alter_tracing_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
