# Generated by Django 5.2.4 on 2025-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HVLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField(verbose_name='Serial Number')),
                ('art_number', models.IntegerField(verbose_name='ART Number')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('date_entered', models.DateField(verbose_name='Date Entered')),
                ('sample_log_number', models.IntegerField(verbose_name='Sample Log Number')),
                ('reason_for_test', models.CharField(max_length=100, verbose_name='Reason for Test')),
                ('result_value', models.IntegerField(verbose_name='Result Value')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
            ],
        ),
    ]
