# Generated by Django 5.2.4 on 2025-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvl_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hvlrecord',
            name='sn',
            field=models.IntegerField(unique=True, verbose_name='Serial Number'),
        ),
    ]
