# Generated by Django 5.2.4 on 2025-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvl_management', '0002_alter_hvlrecord_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hvlrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='hvlrecord',
            name='sn',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Serial Number'),
        ),
    ]
