# Generated by Django 5.2.4 on 2025-10-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvl_management', '0003_remove_hvlrecord_id_alter_hvlrecord_sn'),
        ('pact', '0010_staff_chw_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugResistanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('submit_sample', models.CharField(choices=[('Pending', 'Pending'), ('Yes', 'Yes'), ('No', 'No')], default='Pending', max_length=100, verbose_name='Committee Advice: Submit Sample?')),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('resistance_detected', models.CharField(choices=[('Pending', 'Pending'), ('Yes', 'Yes'), ('No', 'No')], default='Pending', max_length=100, verbose_name='Resistance Detected')),
                ('action_taken', models.CharField(blank=True, choices=[('switch', 'Switch Regimen'), ('continue', 'Continue Current Regimen')], max_length=100, null=True, verbose_name='Action Taken')),
                ('vl_after_action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viral Load 6 Months After Action')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('hvl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_resistance_tests', to='hvl_management.hvlrecord')),
            ],
        ),
        migrations.CreateModel(
            name='IacFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('sample_log_number', models.IntegerField(verbose_name='Sample Log Number')),
                ('result_value', models.IntegerField(blank=True, null=True, verbose_name='Result Value')),
                ('date_given_to_client', models.DateField(blank=True, null=True)),
                ('hvl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iac_follow_ups', to='hvl_management.hvlrecord')),
            ],
        ),
        migrations.CreateModel(
            name='IacSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hvl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iac_sessions', to='hvl_management.hvlrecord')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pact.staff')),
            ],
        ),
    ]
