# Generated by Django 5.2.4 on 2025-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('hcc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField()),
                ('child_birth_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('physical_address', models.TextField()),
                ('agrees_to_fup', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('mother_status', models.CharField(choices=[('Alive No ART', 'Alive No ART'), ('Alive OnART', 'Alive OnART'), ('Died', 'Died'), ('Unknown', 'Unknown')], max_length=20)),
                ('mother_art_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_art_start_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
