# Generated by Django 5.2.4 on 2025-07-22 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('hcc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=200)),
                ('child_dob', models.DateField()),
                ('child_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('child_birth_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guardian_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(default='Mother', max_length=100)),
                ('guardian_phone', models.CharField(default='None', max_length=20)),
                ('physical_address', models.TextField()),
                ('agrees_to_fup', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('mother_status', models.CharField(choices=[('Alive No ART', 'Alive No ART'), ('Alive OnART', 'Alive OnART'), ('Died', 'Died'), ('Unknown', 'Unknown')], default='Alive OnART', max_length=20)),
                ('mother_art_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_art_start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muac', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('wasting', models.CharField(blank=True, choices=[('No', 'No Wasting'), ('Mod', 'Moderate'), ('Sev', 'Severe')], default='No', max_length=4, null=True)),
                ('breastfeeding', models.CharField(blank=True, choices=[('Exc', 'Exclusive'), ('M', 'Mixed/Complement'), ('<6', 'Stopped last 6 Weeks'), ('C', 'Stopped over 6w. ago')], default='Exc', max_length=10, null=True)),
                ('mother_art_status', models.CharField(blank=True, choices=[('No ART', 'Alive No ART'), ('On ART', 'Alive On ART'), ('Died', 'Died'), ('Unk', 'Unknown')], default='On ART', max_length=10, null=True)),
                ('clinical_monitoring', models.CharField(blank=True, choices=[('NAD', 'No Abnormality Detected'), ('Sick', 'Sick child')], default='NAD', max_length=10, null=True)),
                ('hiv_testing', models.CharField(blank=True, choices=[('No', 'Not done'), ('Dbs', 'Dried Blood Spot (PCR)'), ('Rt', 'Rapid Test')], default='No', max_length=10, null=True)),
                ('infection_status', models.CharField(blank=True, choices=[('A', 'Not Infected'), ('B', 'Infected'), ('C', 'Not ART Eligible'), ('D', 'PSHD -> ART')], default='C', max_length=20, null=True)),
                ('drug_given', models.CharField(blank=True, choices=[('None', 'No Drugs Given'), ('CPT', 'Cotrimoxazole Prophylaxis (CPT)'), ('NVP', 'Nevirapine (NVP)'), ('2P', '2P')], default='CPT', max_length=10, null=True)),
                ('cpt_given', models.PositiveIntegerField(blank=True, help_text='Number of CPT/NVP tablets given', null=True)),
                ('follow_up_outcome', models.CharField(choices=[('Con', 'Continue FUP'), ('Dis', 'Discharged'), ('ART', 'Started ART'), ('To', 'Transferred Out'), ('Def', 'Defaulted'), ('Died', 'Died')], default='Con', max_length=10)),
                ('art_number', models.IntegerField(blank=True, null=True)),
                ('next_appointment_or_outcome_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='children.child')),
            ],
        ),
        migrations.CreateModel(
            name='HTSSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('test_type', models.CharField(choices=[('DBS', 'Dried Blood Spot'), ('Rapid', 'Rapid Test')], max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('DBS_6wks_Ini', 'DBS 6 Weeks Initial'), ('DBS_6wks_Con', 'DBS 6 Weeks Confirmatory'), ('DBS_Rapid_Conf', 'DBS Rapid Confirmatory'), ('Rapid_1yr', 'Rapid @ 1yr'), ('Rapid_2yr', 'Rapid @ 2yr')], max_length=30, null=True)),
                ('sample_id', models.CharField(max_length=50)),
                ('result', models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Inconclusive', 'Inconclusive')], max_length=20, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hts_samples', to='children.child')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
