# Generated by Django 5.2.4 on 2025-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='follow_up_outcome',
            field=models.CharField(blank=True, choices=[('Con', 'Continue FUP'), ('Dis', 'Discharged'), ('ART', 'Started ART'), ('To', 'Transferred Out'), ('Def', 'Defaulted'), ('Died', 'Died')], default='Con', max_length=10, null=True),
        ),
    ]
