# Generated by Django 5.2.4 on 2025-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_name',
            field=models.CharField(max_length=200),
        ),
    ]
