# Generated by Django 5.2.4 on 2025-07-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_child_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muac', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('wasting', models.CharField(choices=[('No', 'No Wasting'), ('Mod', 'Moderate'), ('Sev', 'Severe')], max_length=4)),
                ('breastfeeding', models.CharField(choices=[('Exc', 'Exclusive'), ('M', 'Mixed'), ('<6', 'Stopped <6m'), ('C', 'Complementary'), ('Stopped', 'Stopped')], max_length=10)),
                ('mother_art_status', models.CharField(choices=[('No ART', 'Alive No ART'), ('On ART', 'Alive On ART'), ('Died', 'Died'), ('Unk', 'Unknown')], max_length=10)),
                ('clinical_monitoring', models.CharField(choices=[('NAD', 'No Abnormality Detected'), ('Sick', 'Sick child')], max_length=10)),
                ('hiv_testing', models.CharField(choices=[('No', 'Not done'), ('Dbs', 'Dried Blood Spot'), ('Rt', 'Rapid Test'), ('PCR', 'PCR Test')], max_length=10)),
                ('infection_status', models.CharField(choices=[('A', 'Confirmed infected'), ('B', 'Not confirmed'), ('C', 'Not infected'), ('D', 'No ART despite eligibility'), ('PSHD-ART', 'Psychosocial delay to ART')], max_length=20)),
                ('cpt_given', models.PositiveIntegerField(blank=True, help_text='Number of CPT tablets given', null=True)),
                ('follow_up_outcome', models.CharField(choices=[('Con', 'Continue FUP'), ('Dis', 'Discharged'), ('ART', 'Started ART'), ('To', 'Transferred Out'), ('Def', 'Defaulted'), ('Died', 'Died')], max_length=10)),
                ('next_appointment_or_outcome_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='children.child')),
            ],
        ),
    ]
