# Generated by Django 5.2.4 on 2025-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_htssample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='breastfeeding',
            field=models.CharField(blank=True, choices=[('Exc', 'Exclusive'), ('M', 'Mixed'), ('<6', 'Stopped <6m'), ('C', 'Complementary'), ('Stopped', 'Stopped')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='clinical_monitoring',
            field=models.CharField(blank=True, choices=[('NAD', 'No Abnormality Detected'), ('Sick', 'Sick child')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='hiv_testing',
            field=models.CharField(blank=True, choices=[('No', 'Not done'), ('Dbs', 'Dried Blood Spot (PCR)'), ('Rt', 'Rapid Test')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='infection_status',
            field=models.CharField(blank=True, choices=[('A', 'Confirmed infected'), ('B', 'Not confirmed'), ('C', 'Not infected'), ('D', 'Not Eligible for ART')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='mother_art_status',
            field=models.CharField(blank=True, choices=[('No ART', 'Alive No ART'), ('On ART', 'Alive On ART'), ('Died', 'Died'), ('Unk', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='wasting',
            field=models.CharField(blank=True, choices=[('No', 'No Wasting'), ('Mod', 'Moderate'), ('Sev', 'Severe')], max_length=4, null=True),
        ),
    ]
