# Generated by Django 5.2.4 on 2025-07-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_alter_childvisit_breastfeeding_and_more'),
        ('children', '0007_systemlog'),
    ]

    operations = [
    ]
