# Generated by Django 5.2.4 on 2025-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_childvisit_drug_given_alter_childvisit_breastfeeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='breastfeeding',
            field=models.CharField(blank=True, choices=[('Exc', 'Exclusive'), ('M', 'Mixed/Complement'), ('<6', 'Stopped last 6 Weeks'), ('C', 'Stopped over 6w. ago')], default='Exc', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='clinical_monitoring',
            field=models.CharField(blank=True, choices=[('NAD', 'No Abnormality Detected'), ('Sick', 'Sick child')], default='NAD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='drug_given',
            field=models.CharField(blank=True, choices=[('None', 'No Drugs Given'), ('CPT', 'Cotrimoxazole Prophylaxis (CPT)'), ('NVP', 'Nevirapine (NVP)'), ('2P', '2P')], default='CPT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='follow_up_outcome',
            field=models.CharField(choices=[('Con', 'Continue FUP'), ('Dis', 'Discharged'), ('ART', 'Started ART'), ('To', 'Transferred Out'), ('Def', 'Defaulted'), ('Died', 'Died')], default='Con', max_length=10),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='hiv_testing',
            field=models.CharField(blank=True, choices=[('No', 'Not done'), ('Dbs', 'Dried Blood Spot (PCR)'), ('Rt', 'Rapid Test')], default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='infection_status',
            field=models.CharField(blank=True, choices=[('A', 'Not Infected'), ('B', 'Infected'), ('C', 'Not ART Eligible'), ('D', 'PSHD -> ART')], default='C', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='mother_art_status',
            field=models.CharField(blank=True, choices=[('No ART', 'Alive No ART'), ('On ART', 'Alive On ART'), ('Died', 'Died'), ('Unk', 'Unknown')], default='On ART', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='wasting',
            field=models.CharField(blank=True, choices=[('No', 'No Wasting'), ('Mod', 'Moderate'), ('Sev', 'Severe')], default='No', max_length=4, null=True),
        ),
    ]
