# Generated by Django 5.2.4 on 2025-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0011_alter_childvisit_breastfeeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='agrees_to_fup',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_phone',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_status',
            field=models.CharField(choices=[('Alive No ART', 'Alive No ART'), ('Alive OnART', 'Alive OnART'), ('Died', 'Died'), ('Unknown', 'Unknown')], default='Alive OnART', max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='relationship',
            field=models.CharField(default='Mother', max_length=100),
        ),
    ]
