# Generated by Django 5.2.4 on 2025-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0013_htssample_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='art_number',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
