# Generated by Django 5.2.4 on 2025-07-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0014_childvisit_art_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
