# Generated by Django 5.2.4 on 2025-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0015_alter_childvisit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htssample',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
