# Generated by Django 5.2.4 on 2025-07-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('arv_number', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('birthdate', models.DateField()),
                ('outcome', models.CharField(choices=[('On antiretrovirals', 'On antiretrovirals'), ('Patient transferred out', 'Patient transferred out'), ('Defaulted', 'Defaulted'), ('Patient died', 'Patient died'), ('Treatment stopped', 'Treatment stopped')], max_length=50)),
                ('art_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cadre', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Supervisor', 'Supervisor'), ('Statistcal Clerk', 'Statistical Clerk'), ('HDA/Treatment Supporter', 'HDA/Treatment Supporter'), ('Treatment Supporter', 'Treatment Supporter')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateField()),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, choices=[('Email', 'Email'), ('Portal', 'Portal'), ('Courier', 'Courier'), ('In-person', 'In-person')], max_length=20, null=True)),
                ('test_reason', models.CharField(blank=True, choices=[('Medical examination, routine', 'Routine Examination'), ('Diagnostic test', 'Diagnostic Test'), ('Follow-up', 'Follow-up')], max_length=100, null=True)),
                ('tat_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arv_number', models.ForeignKey(db_column='arv_number', on_delete=django.db.models.deletion.CASCADE, to='pact.patient')),
            ],
            options={
                'db_table': 'lab_results',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandson', 'Grandson'), ('granddaughter', 'Granddaughter'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('cousin', 'Cousin'), ('husband', 'Husband'), ('wife', 'Wife'), ('stepfather', 'Stepfather'), ('stepmother', 'Stepmother'), ('stepson', 'Stepson'), ('stepdaughter', 'Stepdaughter'), ('stepbrother', 'Stepbrother'), ('stepsister', 'Stepsister'), ('father_in_law', 'Father-in-law'), ('mother_in_law', 'Mother-in-law'), ('brother_in_law', 'Brother-in-law'), ('sister_in_law', 'Sister-in-law'), ('son_in_law', 'Son-in-law'), ('daughter_in_law', 'Daughter-in-law'), ('ex_husband', 'Ex-husband'), ('ex_wife', 'Ex-wife'), ('boyfriend', 'Boyfriend'), ('girlfriend', 'Girlfriend'), ('fiance', 'Fiancé/Fiancée'), ('partner', 'Partner'), ('significant_other', 'Significant Other'), ('ex_partner', 'Ex-Partner'), ('friend', 'Friend'), ('best_friend', 'Best Friend'), ('neighbor', 'Neighbor'), ('roommate', 'Roommate'), ('classmate', 'Classmate'), ('teammate', 'Teammate'), ('companion', 'Companion'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('boss', 'Boss'), ('colleague', 'Colleague'), ('employee', 'Employee'), ('client', 'Client'), ('supervisor', 'Supervisor'), ('intern', 'Intern'), ('contractor', 'Contractor'), ('business_partner', 'Business Partner'), ('teacher', 'Teacher'), ('student', 'Student'), ('principal', 'Principal'), ('tutor', 'Tutor'), ('advisor', 'Advisor'), ('primary_caregiver', 'Primary Caregiver'), ('legal_guardian', 'Legal Guardian'), ('emergency_contact', 'Emergency Contact'), ('healthcare_proxy', 'Healthcare Proxy'), ('social_worker', 'Social Worker'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('power_of_attorney', 'Power of Attorney'), ('trustee', 'Trustee'), ('executor', 'Executor')], max_length=255)),
                ('on_art', models.BooleanField()),
                ('facility', models.CharField(max_length=255)),
                ('art_number', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='pact.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('reason', models.CharField(choices=[('Treatment failure', 'Treatment failur'), ('Targeted', 'Targeted')], max_length=50)),
                ('result', models.CharField(blank=True, choices=[('Resistance Detected', 'Resistance Detected'), ('Resistance Not Detected', 'Resistance Not Detected')], max_length=50, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genotypes', to='pact.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regimen', models.CharField(blank=True, max_length=5, null=True)),
                ('arv_number', models.ForeignKey(db_column='arv_number', on_delete=django.db.models.deletion.CASCADE, to='pact.patient')),
            ],
            options={
                'db_table': 'regimen',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('STD 1', 'Standard 1'), ('STD 2', 'Standard 2'), ('STD 3', 'Standard 3'), ('STD 4', 'Standard 4'), ('STD 5', 'Standard 5'), ('STD 6', 'Standard 6'), ('STD 7', 'Standard 7'), ('STD 8', 'Standard 8'), ('FORM 1', 'Form 1'), ('FORM 2', 'Form 2'), ('FORM 3', 'Form 3'), ('FORM 4', 'Form 4'), ('College', 'College')], max_length=11)),
                ('boarding_type', models.CharField(choices=[('self_boarding', 'Self-Boarding'), ('full_boarding', 'Full Boarding'), ('day_scholar', 'Day Scholar'), ('weekly_boarding', 'Weekly Boarding'), ('partial_boarding', 'Partial Boarding')], max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='pact.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_date', models.DateField()),
                ('experts_present', models.TextField()),
                ('feedback', models.TextField()),
                ('follow_up_actions', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='pact.patient')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='pact.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('guardian_presence', models.BooleanField()),
                ('adherence_challenges', models.TextField()),
                ('psychosocial_issues', models.TextField(blank=True, null=True)),
                ('home_environment', models.TextField(blank=True, null=True)),
                ('school_issues', models.TextField(blank=True, null=True)),
                ('proposed_solutions', models.TextField(blank=True, null=True)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='pact.patient')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='pact.staff')),
            ],
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chw', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village', to='pact.patient')),
            ],
        ),
    ]
