# Generated by Django 5.2.4 on 2025-07-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='outcome',
            field=models.CharField(choices=[('On antiretrovirals', 'On antiretrovirals'), ('Patient transferred out', 'Patient transferred out'), ('Defaulted', 'Defaulted'), ('Patient died', 'Patient died'), ('Treatment stopped', 'Treatment stopped')], max_length=50),
        ),
    ]
