# Generated by Django 5.2.4 on 2025-07-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimen',
            name='arvs',
            field=models.CharField(default='tdf', max_length=255),
            preserve_default=False,
        ),
    ]
