# Generated by Django 5.2.4 on 2025-07-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0002_regimen_arvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='chw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='pact.staff'),
        ),
    ]
