# Generated by Django 5.2.4 on 2025-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0003_alter_village_chw'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='name',
            field=models.CharField(default='kapinjiri', max_length=255),
            preserve_default=False,
        ),
    ]
