# Generated by Django 5.2.4 on 2025-07-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0004_village_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
