# Generated by Django 5.2.4 on 2025-07-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0005_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
