# Generated by Django 5.2.4 on 2025-07-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0006_guardian_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='vl_status',
            field=models.CharField(choices=[('Suppressed', 'Suppressed'), ('High', 'High'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
