# Generated by Django 5.2.4 on 2025-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0007_guardian_vl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='actions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
