# Generated by Django 5.2.4 on 2025-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0008_patient_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='actions',
            field=models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Stopped', 'Stopped')], max_length=255, null=True),
        ),
    ]
