# Generated by Django 5.2.4 on 2025-09-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0009_patient_notes_alter_patient_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='chw_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
