# Generated by Django 5.2.4 on 2025-07-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_type', models.CharField(choices=[('Patient Only', 'Patient Only'), ('Guardian Only', 'Guardian Only'), ('Both Patient & Guardian', 'Both Patient & Guardian')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='pact.patient')),
            ],
        ),
    ]
