# Generated by Django 5.2.4 on 2025-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='arv_given',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childvisit',
            name='cpt_given',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childvisit',
            name='next_outcome_date',
            field=models.DateField(default='2024-06-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childvisit',
            name='side_effect',
            field=models.CharField(choices=[('NO', 'NO'), ('PN', 'PN'), ('HP', 'HP'), ('SK', 'SK'), ('LIP', 'LIP'), ('OTH', 'OTH')], default='NO', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childvisit',
            name='tab_status',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y'), ('C', 'C'), ('Rx', 'Rx')], default='N', max_length=2),
            preserve_default=False,
        ),
    ]
