# Generated by Django 5.2.4 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_childvisit_arv_given_childvisit_cpt_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='side_effect',
            field=models.CharField(choices=[('NO', 'NO'), ('PN', 'PN'), ('HP', 'HP'), ('SK', 'SK'), ('LIP', 'LIP'), ('OTH', 'OTH')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='tab_status',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y'), ('C', 'C'), ('Rx', 'Rx')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='visit_type',
            field=models.CharField(choices=[('Patient Only', 'Patient Only'), ('Guardian Only', 'Guardian Only'), ('Both Patient & Guardian', 'Both Patient & Guardian')], default='Patient Only', max_length=50),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
