# Generated by Django 5.2.4 on 2025-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_childvisit_side_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
