# Generated by Django 5.2.4 on 2025-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_childvisit_visit_date_alter_childvisit_weight'),
        ('pact', '0007_guardian_vl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='childvisit',
            constraint=models.UniqueConstraint(fields=('patient', 'visit_date'), name='unique_patient_visit'),
        ),
    ]
