# Generated by Django 5.2.4 on 2025-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_alter_childvisit_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='regimen',
            field=models.CharField(default='12A', max_length=4),
            preserve_default=False,
        ),
    ]
