# Generated by Django 5.2.4 on 2025-07-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_childvisit_regimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='pill_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
