# Generated by Django 5.2.4 on 2025-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_childvisit_pill_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='viral_load',
            field=models.CharField(choices=[('Not Bled', 'Not Bled'), ('BLED', 'BLED'), ('Result', 'Result')], default='Not Bled', max_length=50),
        ),
    ]
