# Generated by Django 5.2.4 on 2025-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_childvisit_viral_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='tpt_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childvisit',
            name='tpt_given',
            field=models.CharField(blank=True, choices=[('Not Given', 'Not Given'), ('3HP', '3HP'), ('INH', 'INH')], default='Not Given', max_length=9, null=True),
        ),
    ]
