# Generated by Django 5.2.4 on 2025-07-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_childvisit_tpt_amount_childvisit_tpt_given'),
        ('pact', '0007_guardian_vl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artvisits', to='pact.patient'),
        ),
    ]
