# Generated by Django 5.2.4 on 2025-08-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_alter_childvisit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='entry_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Backlog', 'Backlog')], default='Backlog', max_length=7),
            preserve_default=False,
        ),
    ]
