# Generated by Django 5.2.4 on 2025-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_childvisit_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='entry_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Backlog', 'Backlog')], default='Normal', max_length=7),
        ),
    ]
