# Generated by Django 5.2.4 on 2025-08-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_alter_childvisit_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childvisit',
            name='entry_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Backlog', 'Backlog')], default='Backlog', max_length=7),
        ),
    ]
